development:
  adapter: postgresql
  database: memory_lane_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: memory_lane_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: memory_lane_production
  pool: 5
  timeout: 5000